### ISSUE TITLE
-usecoherent no longer works (fixed)

### ISSUE THREAD

**Issue by asmaloney** [asmaloney/GuildWars2-macOS#8] opened 2023-07-18 21:50 UTC
### macOS Version

any

### WineskinServer Version

any

### Wine Engine Version

any

### Problem

As of the **18 July 2023** GW2 update, it seems the `-usecoherent` switch no longer works.

This means that GW2 is not playable anymore using WINE.

If I figure out a workaround I will update this issue. Otherwise... I guess it's on to other games...

### Additional Information

**Update:** See the section **Tweaking Config** in [the tutorial](https://asmaloney.com/2022/07/howto/running-guild-wars-2-with-dx11-on-macos-using-wine/). It seems to be working for people.

**Comment by GeorgeH9292** [comment] 2023-07-19 13:37
damn them, can't believe they've done this to us. I had just purchased the new expansion and started getting back into gw2

**Comment by GeorgeH9292** [comment] 2023-07-19 13:47
looks like might need to pay for parellels to emulate a Windows 11 on Mac book pro M1 chip. I'm going to try the 14 day trial and give it a go

**Comment by asmaloney** [comment] 2023-07-19 17:20
Multiple people have pointed out that you can skip installing the _winetricks_ and it will run. I tried it and get about 10 FPS, so it's unplayable for me without _dxvk_.

**Comment by GeorgeH9292** [comment] 2023-07-19 17:49
Yeah no good playing at 10fps. I’ve nearly finished downloading for Parallel with the 14 day trial, the trial version doesn’t run at maximum cores and ram like winetricks so won’t be an exact comparison. I don’t get why they don’t just bring back an iOS executable for gw2, they will lose a lot of players I think if can’t play it reliably

**Comment by asmaloney** [comment] 2023-07-20 20:57
Good news!

@Gcenx gave me a workaround that seems to be working.

See the section **Tweaking Config** in [the tutorial](https://asmaloney.com/2022/07/howto/running-guild-wars-2-with-dx11-on-macos-using-wine/).

**Comment by GeorgeH9292** [comment] 2023-07-21 06:09
Excellent will try this soon

**Comment by Gcenx** [comment] 2023-07-23 18:33
I’ve altered the DXVK verbs provided by Wineskin so they no longer install DXVK dxgi this avoids the issues seen in GuildWars2 and many other launchers.

**Comment by asmaloney** [comment] 2023-07-23 19:43
That's fantastic! Thanks so much Dean.

**Comment by GeorgeH9292** [comment] 2023-07-24 07:41
the instructions are slightly off, you need to add the dxgi library, before you can then edit it

**Comment by asmaloney** [comment] 2023-07-24 07:50
I think with Dean's changes that step (changing stuff with dxgi) shouldn't be needed anymore though. I'll have to give it a try from scratch and update the post.

**Comment by GeorgeH9292** [comment] 2023-07-24 07:52
oh ok, well I am installing a new wrapper with everything like normal, but have added in the config for dxgi update. Should I stop and create a new wrapper and do nothing?

**Comment by asmaloney** [comment] 2023-07-24 07:56
Yes - as long as you update winetricks before installing dxvk I think it should work.

**Comment by GeorgeH9292** [comment] 2023-07-24 08:57
ok I've done that instead of the tweak config and is downloading properly, so will see how we go

**Comment by Gcenx** [comment] 2023-07-31 14:46
The issue is fully resolved in WineCX22.1.1-10.

**Closed as completed** 2023-12-30 14:33 UTC
